spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth-app}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Pandey7759@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:mrpandey7759@gmail.com}
    password: ${MAIL_PASSWORD:kjyqqxbhkintivjg}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}

          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}

logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:A9kP3mX7vQ2rL8sN5dF1hJ6wZ4cT0yB8uV3gM7pR2xK9nL5sD1qW6eH8jC4zF0aX7mP2kL9vR5sN8}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: false
    cookie-http-only: true
    cookie-same-site: Lax
    cookie-domain: localhost

file:
  upload-dir: uploads

app:
  cors:
    front-end-url: ${FRONT_END_URL:http://localhost:5173}

  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT:http://localhost:5173/oauth/success}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT:http://localhost:5173/oauth/failure}
      reset-url: ${FRONT_END_RESET_URL:http://localhost:5173/reset-password}

    msg91:
      auth:
        key: ${MSG91_AUTH_KEY:test-key}
      template:
        id: ${MSG91_TEMPLATE_ID:test-template-id}