spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:None}
    cookie-domain: ${JWT_COOKIE_DOMAIN:}

file:
  upload-dir: ${FILE_UPLOAD_DIR:/tmp/uploads}

app:
  cors:
    front-end-url: ${FRONT_END_URL}

  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT}
      reset-url: ${FRONT_END_RESET_URL}

    msg91:
      auth:
        key: ${MSG91_AUTH_KEY}
      template:
        id: ${MSG91_TEMPLATE_ID}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}